### ISSUE TITLE
Configure Eureka client to notify of the correct Hostname for Docker swarm mode

### ISSUE THREAD

**Issue by abhijitvk** [department-of-veterans-affairs/ascent-dashboard#4]
Modify bootstrap.yml file to add the below 2 keys for all the **docker** profiles, so that eureka client is notified with the correct hostname.

```
   eureka:
      instance:
        hostname: "@project.artifactId@"
        preferIpAddress: false
```
